language: node_js

notifications:
  email: false

node_js:
  - "12.16.1"
      
services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.4

before_install:
  - cd gostyle-couponing-api

install: npm install

before_script:
  - cp -a .env.example .env
  - psql -c "CREATE DATABASE gostyle;" -U postgres
  - psql -c "CREATE USER gostyle WITH PASSWORD 'password';" -U postgres
  - sudo psql -c "ALTER USER gostyle WITH SUPERUSER;" -U postgres
  - sudo psql -c 'create extension if not exists "uuid-ossp";' -U postgres

jobs:
  include:
    - stage: Tests
      if: |
        branch = develop AND \
        tag IS blank
      script: 
        - npm run lint
        - npm run test:coverage
        - npm run test:coveralls

cache:
  directories:
    - node_modules

sudo: required