language: node_js

notifications:
  email: false

node_js:
  - "12.16.1"
      
services:
  - postgresql

addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

before_install:
  - cd gostyle-couponing-api

install: npm install

before_script:
  - cp -a .env.example .env
  - psql -c 'create extension if not exists "postgis";' -U postgres
  - psql -c 'create extension if not exists "uuid-ossp";' -U postgres
  - psql -c "CREATE DATABASE gostyle;" -U postgres
  - psql -c "CREATE USER gostyle WITH PASSWORD 'password';" -U postgres

jobs:
  include:
    - stage: Tests
      if: |
        branch = develop AND \
        tag IS blank
      script: 
        - npm run lint
        - npm run test:coverage
        - npm run test:coveralls

cache:
  directories:
    - node_modules