version: '3.7'

services:
  gostyle-couponing-api:
    container_name: gostyle-couponing-api
    hostname: gostyle-couponing-api
    build:
      context: ../gostyle-couponing-api/
      dockerfile: Dockerfile
    image: gostyle-couponing-api:latest
    restart: always
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    network_mode: host
    depends_on:
      - gostyle-database
    command: npm run start

  gostyle-database:
    container_name: gostyle-database
    hostname: gostyle-database
    image: postgres:9.6.15-alpine
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gostyle
