version: '3.7'

services:
  gostyle-couponing-api:
    container_name: gostyle-couponing-api
    hostname: gostyle-couponing-api
    build:
      context: ../gostyle-couponing-api/
      dockerfile: Dockerfile
    image: gostyle-couponing-api:latest
    restart: unless-stopped
    volumes:
      - ../gostyle-couponing-api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - gostyle-database
    command: npm run dev

  gostyle-front-admin:
    container_name: gostyle-front-admin
    hostname: gostyle-front-admin
    build:
      context: ../gostyle-front-admin/
      dockerfile: Dockerfile
    image: gostyle-front-admin:latest
    restart: unless-stopped
    volumes:
      - ../gostyle-front-admin:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on: 
      - gostyle-couponing-api
    command: npm run serve

  gostyle-database:
    container_name: gostyle-database
    hostname: gostyle-database
    image: postgres:9.6.15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gostyle
